name: Matrix configuration
on:
    push:
    workflow_dispatch:

jobs:
    deploy-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Echo docer details
              run: docker info
              
            - name: Run images
              run: docker run hello-world
              
    deploy-windows:
        runs-on: windows-latest
        steps:
            - name: Echo docer details
              run: docker info
              
            - name: Run images
              run: docker run hello-world
                        